# global options
safe: true

# content
include: ["_modules", "_static"]
exclude: ["Gemfile", "Gemfile.lock", "Session.vim"]
show_drafts: null
future: false
lsi: false

# rendering
markdown: kramdown
highlighter: rouge
