# global options
safe: true

# content
include: ["_modules", "_static"]
exclude: ["Gemfile", "Gemfile.lock", "Session.vim"]
show_drafts: null
future: false

# presentation
permalink: /:categories/:title
lsi: false

# conversion
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
highlighter: rouge
