# global options
safe: true

# content
include: ["_modules", "_static"]
exclude: ["Gemfile", "Gemfile.lock", "Session.vim"]
show_drafts: false
future: false

# presentation
permalink: /:categories/:title
lsi: false

# conversion
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM
    hard_wrap: false
    line_width: 120
    syntax_highlighter: rouge
    default_lang: cpp

# variables
title: Devlog
